INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());

INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Books', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, createdAt)  VALUES ('Computers' NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Livros', NOW());
